[versions]
agp = "8.13.0"
kotlin = "2.2.20"
compose = "1.9.0"
savedstate = "1.4.0-alpha03"
nav3Core = "1.0.0-alpha10"

[libraries]
savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }

